# Generated by Django 3.2.16 on 2023-05-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data', models.DateField(verbose_name='Data')),
                ('arquivos1', models.FileField(blank=True, default='', upload_to='Arquivo', verbose_name='Anexar Arquivo')),
                ('arquivos2', models.FileField(blank=True, default='', upload_to='Arquivo', verbose_name='Anexar Arquivo')),
                ('arquivos3', models.FileField(blank=True, default='', upload_to='Arquivo', verbose_name='Anexar Arquivo')),
            ],
        ),
    ]
