# Generated by Django 3.2.16 on 2023-05-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistencia2', models.CharField(max_length=100, verbose_name='Assistencia')),
            ],
        ),
        migrations.CreateModel(
            name='Serviço',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistencia2', models.CharField(help_text='Informe Assistência', max_length=100, verbose_name='Assistência')),
                ('valoros', models.CharField(blank=True, default='', max_length=100, verbose_name='Valor OS')),
                ('valorterceirizado', models.CharField(blank=True, default='', max_length=100, verbose_name='Valor Terceirizado')),
                ('clientesegurado', models.CharField(default='', max_length=100, verbose_name='Cliente/Segurado')),
                ('endereco', models.TextField(default='', max_length=1000, verbose_name='Endereço')),
                ('servico', models.CharField(max_length=100, verbose_name='Serviço')),
                ('data', models.DateField(verbose_name='Data')),
                ('senha', models.CharField(blank=True, default='', max_length=100, verbose_name='Senha')),
                ('cidadeestado', models.CharField(default='', max_length=100, verbose_name='Cidade/Estado')),
                ('telefone', models.CharField(blank=True, default='', max_length=100, verbose_name='Telefone')),
                ('material', models.CharField(blank=True, default='', max_length=100, verbose_name='Material')),
                ('empresa', models.CharField(default='', max_length=1000, verbose_name='Empresa/Seguro')),
                ('decricao', models.TextField(blank=True, default='', max_length=1000, verbose_name='Descrição')),
                ('foto', models.FileField(blank=True, default='', help_text='Coloque Assinatura/Checklist', upload_to='media', verbose_name='Anexar Imagem')),
                ('foto2', models.FileField(blank=True, default='', help_text='Coloque Assinatura/Checklist', upload_to='media', verbose_name='Anexar Imagem')),
                ('foto3', models.FileField(blank=True, default='', help_text='Coloque Assinatura/Checklist', upload_to='media', verbose_name='Anexar Imagem')),
                ('foto4', models.FileField(blank=True, default='', help_text='Coloque Assinatura/Checklist', upload_to='media', verbose_name='Anexar Imagem')),
            ],
        ),
    ]
